---
name: HTGT

using_frontend_proxy: 1

session:
  expires: 3600
  dbi_dbh: HTGTDB
  dbi_table: sessions

global_home:
   migt: '/lustre/scratch103/sanger/vvi/vector_design/migt/global_home'
   migp: '/lustre/scratch103/sanger/vvi/vector_design/migp/global_home'
   migp_b: '/lustre/scratch103/sanger/vvi/vector_design/migp/global_home'
   migp_ha: '/lustre/scratch103/sanger/vvi/vector_design/migp/global_home'

designurl:
  migp_ha: 'http://migsrv1a.internal.sanger.ac.uk:8083'
  migt: 'http://migsrv1a.internal.sanger.ac.uk:8082'

# Think this forces everything below root/static to be served statically
#  as well as the default of all .png .gif .css below root/
# Should ensure consistent behaviour between a perl server and an apache server 
#  with a <Location /{htgt/,}static> SetHandler default-handler config
static:
  dirs:
    - static

banned_hosts:
  - .search.msn.com
  - .googlebot.com
  - .cuil.com
  - .crawl.yahoo.net

authentication:
  realms:
    ssso:
      credential:
        class: +HTGT::Mock::Credential
      store:
        class: +HTGT::Mock::Store
