CREATE SEQUENCE "EUCOMM_VECTOR"."S_GRC_RESEQ_ID";
CREATE TABLE "EUCOMM_VECTOR"."GRC_RESEQ" ("GRC_RESEQ_ID" NUMBER NOT NULL PRIMARY KEY, "GR_GENE_STATUS_ID" NUMBER NOT NULL REFERENCES GR_GENE_STATUS(GR_GENE_STATUS_ID) ON DELETE CASCADE, "TARGVEC_WELL_ID" NUMBER NOT NULL REFERENCES WELL(WELL_ID), "VALID_PRIMERS" VARCHAR2(200 CHAR) NOT NULL);
CREATE OR REPLACE TRIGGER "EUCOMM_VECTOR"."TR_GRC_RESEQ_ID"
    before insert on "GRC_RESEQ"
        for each row begin
            if inserting then
                if :NEW."GRC_RESEQ_ID" is null then
                    select S_GRC_RESEQ_ID.nextval into :NEW."GRC_RESEQ_ID" from dual;
                end if;
            end if;
        end;
/
ALTER TRIGGER "EUCOMM_VECTOR"."TR_GRC_RESEQ_ID" ENABLE;
CREATE UNIQUE INDEX GRC_RESEQ_TARGVEC_WELL ON GRC_RESEQ ( TARGVEC_WELL_ID );

INSERT INTO GR_VALID_STATE VALUES ('reseq-c','Candidate for resequencing');
INSERT INTO GR_VALID_STATE VALUES ('reseq', 'In resequencing recovery' );
