
  CREATE TABLE "EUCOMM_VECTOR"."QC_RUNS" 
   (	"QC_RUN_ID" CHAR(36 CHAR) NOT NULL ENABLE, 
	"QC_RUN_DATE" TIMESTAMP (6) DEFAULT current_timestamp NOT NULL ENABLE, 
	"SEQUENCING_PROJECT" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"PROFILE" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"TEMPLATE_PLATE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SOFTWARE_VERSION" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "QC_RUNS_PK" PRIMARY KEY ("QC_RUN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_RUNS_PLATE_FK1" FOREIGN KEY ("TEMPLATE_PLATE_ID")
	  REFERENCES "EUCOMM_VECTOR"."PLATE" ("PLATE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;

  CREATE TABLE "EUCOMM_VECTOR"."QC_SEQ_READS" 
   (	"QC_SEQ_READ_ID" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"COMMENT" VARCHAR2(200 CHAR) DEFAULT '' NOT NULL ENABLE, 
	"FASTA" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "QC_SEQ_READS_PK" PRIMARY KEY ("QC_SEQ_READ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" 
 LOB ("FASTA") STORE AS SECUREFILE (
  TABLESPACE "DATA_02" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE TABLE "EUCOMM_VECTOR"."QC_SYNVECS" 
   (	"QC_SYNVEC_ID" CHAR(40 CHAR) NOT NULL ENABLE, 
	"DESIGN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CASSETTE" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"BACKBONE" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"APPLY_FLP" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"APPLY_CRE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"GENBANK" CLOB NOT NULL ENABLE, 
	"VECTOR_STAGE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "QC_SYNVECS_PK" PRIMARY KEY ("QC_SYNVEC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_SYNVECS_CHK1" CHECK (apply_flp in (0,1)) ENABLE, 
	 CONSTRAINT "QC_SYNVECS_CHK2" CHECK (apply_cre in (0,1)) ENABLE, 
	 CONSTRAINT "QC_SYNVECS_CHK3" CHECK (
vector_stage in ( 'final', 'intermediate' )
) ENABLE, 
	 CONSTRAINT "QC_SYNVECS_DESIGN_FK1" FOREIGN KEY ("DESIGN_ID")
	  REFERENCES "EUCOMM_VECTOR"."DESIGN" ("DESIGN_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" 
 LOB ("GENBANK") STORE AS SECUREFILE (
  TABLESPACE "DATA_02" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."QC_SYNVECS_PK" ON "EUCOMM_VECTOR"."QC_SYNVECS" ("QC_SYNVEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;
  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."SYS_IL0000101929C00007$$" ON "EUCOMM_VECTOR"."QC_SYNVECS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

  CREATE TABLE "EUCOMM_VECTOR"."QC_TEST_RESULTS" 
   (	"QC_TEST_RESULT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QC_RUN_ID" CHAR(36 CHAR) NOT NULL ENABLE, 
	"QC_SYNVEC_ID" CHAR(40 CHAR) NOT NULL ENABLE, 
	"WELL_NAME" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"SCORE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"PASS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "QC_TEST_RESULTS_PK" PRIMARY KEY ("QC_TEST_RESULT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_TEST_RESULTS_UK1" UNIQUE ("QC_RUN_ID", "QC_SYNVEC_ID", "WELL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_TEST_RESULTS_CHK1" CHECK (pass in (0,1)) ENABLE, 
	 CONSTRAINT "QC_TEST_RESULTS_QC_RUNS_FK1" FOREIGN KEY ("QC_RUN_ID")
	  REFERENCES "EUCOMM_VECTOR"."QC_RUNS" ("QC_RUN_ID") ENABLE, 
	 CONSTRAINT "QC_TEST_RESULTS_QC_SYNVEC_FK1" FOREIGN KEY ("QC_SYNVEC_ID")
	  REFERENCES "EUCOMM_VECTOR"."QC_SYNVECS" ("QC_SYNVEC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;

  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."QC_TEST_RESULTS_PK" ON "EUCOMM_VECTOR"."QC_TEST_RESULTS" ("QC_TEST_RESULT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;
  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."QC_TEST_RESULTS_UK1" ON "EUCOMM_VECTOR"."QC_TEST_RESULTS" ("QC_RUN_ID", "QC_SYNVEC_ID", "WELL_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;

  CREATE OR REPLACE TRIGGER "EUCOMM_VECTOR"."QC_TEST_RESULTS_TRG" 
BEFORE INSERT ON QC_TEST_RESULTS
FOR EACH ROW 
BEGIN
  SELECT QC_TEST_RESULTS_SEQ.NEXTVAL INTO :NEW.QC_TEST_RESULT_ID FROM DUAL;
END;

/
ALTER TRIGGER "EUCOMM_VECTOR"."QC_TEST_RESULTS_TRG" ENABLE;

  CREATE TABLE "EUCOMM_VECTOR"."QC_TEST_RESULT_ALIGNMENTS" 
   (	"QC_TEST_RESULT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QC_SEQ_READ_ID" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"PRIMER_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"QUERY_START" NUMBER(10,0) NOT NULL ENABLE, 
	"QUERY_END" NUMBER(10,0) NOT NULL ENABLE, 
	"QUERY_STRAND" NUMBER(1,0) NOT NULL ENABLE, 
	"TARGET_START" NUMBER(10,0) NOT NULL ENABLE, 
	"TARGET_END" NUMBER(10,0) NOT NULL ENABLE, 
	"TARGET_STRAND" NUMBER(1,0) NOT NULL ENABLE, 
	"SCORE" NUMBER(10,0) NOT NULL ENABLE, 
	"PASS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT_PK" PRIMARY KEY ("QC_TEST_RESULT_ID", "QC_SEQ_READ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT_UK1" UNIQUE ("QC_TEST_RESULT_ID", "PRIMER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02"  ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT_CHK1" CHECK (query_strand in (1,-1)) ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT_CHK2" CHECK (target_strand in (1,-1)) ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT_CHK3" CHECK (pass in (0,1)) ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT__FK1" FOREIGN KEY ("QC_SEQ_READ_ID")
	  REFERENCES "EUCOMM_VECTOR"."QC_SEQ_READS" ("QC_SEQ_READ_ID") ENABLE, 
	 CONSTRAINT "QC_TEST_RESULT_ALIGNMENT__FK2" FOREIGN KEY ("QC_TEST_RESULT_ID")
	  REFERENCES "EUCOMM_VECTOR"."QC_TEST_RESULTS" ("QC_TEST_RESULT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;

  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."QC_TEST_RESULT_ALIGNMENT_PK" ON "EUCOMM_VECTOR"."QC_TEST_RESULT_ALIGNMENTS" ("QC_TEST_RESULT_ID", "QC_SEQ_READ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;
  CREATE UNIQUE INDEX "EUCOMM_VECTOR"."QC_TEST_RESULT_ALIGNMENT_UK1" ON "EUCOMM_VECTOR"."QC_TEST_RESULT_ALIGNMENTS" ("QC_TEST_RESULT_ID", "PRIMER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_02" ;

